### ISSUE TITLE
non key-bound credentials

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VP#61] opened 2023-11-13 16:39 UTC
Right now, the specification says:
> This specification assumes that a Verifiable Credential is always presented with a cryptographic proof of possession which can be a Verifiable Presentation.

This would exclude the possibility to send claim-bound credentials, e.g. diplomas as they are used today in the physical world or any VC equivalent to signed PDFs. See also https://github.com/oauth-wg/oauth-sd-jwt-vc/issues/145 

Even the W3C VP does not mandate a proof bound to a key.

Do we want to soften this requirement?

**Comment by c2bo** [comment] 2023-11-22 20:33
I agree, I think there is value / use-cases for attestations without a cryptographic key binding

**Comment by awoie** [comment] 2023-12-12 20:32
potential duplicate of #6

**Comment by Sakurann** [comment] 2024-11-28 21:22
closing as duplicate of #6

**Closed by Sakurann** 2024-11-28 21:22 UTC
